# Generated by Django 4.1.5 on 2023-02-11 11:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='course')),
                ('courseFee', models.IntegerField()),
                ('courseDuration', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('syllabus', ckeditor.fields.RichTextField(default='syllabus')),
                ('aboutCourse', ckeditor.fields.RichTextField(default='aboutCourse')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('candidateId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=20)),
                ('phoneNumber', models.IntegerField()),
                ('alternateNumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('collegeName', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('landMark', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('companyName', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=100)),
                ('computerKnowledge', models.CharField(max_length=50)),
                ('course', models.TextField(blank=True, max_length=350, null=True)),
                ('timeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.IntegerField()),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Unpaid', max_length=20)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riaapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='documents')),
                ('verification', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riaapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate', models.ImageField(upload_to='certificates')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riaapp.register')),
            ],
        ),
    ]
