# Generated by Django 4.1.5 on 2023-02-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0005_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='trainer',
            field=models.ManyToManyField(default='Null', to='riaapp.trainer'),
        ),
    ]
