# Generated by Django 4.1.5 on 2023-02-15 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0006_register_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='trainer',
        ),
        migrations.AddField(
            model_name='register',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='riaapp.trainer'),
        ),
    ]
