# Generated by Django 4.1.5 on 2023-02-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riaapp', '0007_remove_register_trainer_register_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=50)),
                ('logintime', models.CharField(max_length=50)),
                ('logouttime', models.CharField(max_length=50)),
                ('approvalstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
